# Generated by Django 5.0.6 on 2024-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='herotype',
            name='image',
            field=models.ImageField(upload_to='hero/'),
        ),
    ]
